services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: trakto_api_dev
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - ./:/app
      - pnpm-store:/root/.local/share/pnpm/store/v3
    ports:
      - ${PORT}:${PORT}
    networks: [app-tier]

volumes:
  pnpm-store:

networks:
  app-tier:
