services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    container_name: trakto_api_dev
    restart: unless-stopped
    env_file:
      - .env
    depends_on:
      mongo:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    volumes:
      - ./:/app
      - pnpm-store:/root/.local/share/pnpm/store/v3
      - uploads-data:/tmp/uploads
      - images-data:/images
    ports:
      - ${PORT}:${PORT}
    networks: [app-tier]

volumes:
  pnpm-store:

networks:
  app-tier:
