services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    container_name: trakto_api
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - NODE_ENV=${NODE_ENV}
      - MONGODB_URI=mongodb://${MONGODB_USER}:${MONGODB_PASSWORD}@mongo:${MONGODB_PORT}/${MONGODB_DATABASE}?authSource=admin
      - MONGODB_DATABASE=${MONGODB_DATABASE}
      - MONGODB_USER=${MONGODB_USER}
      - MONGODB_PASSWORD=${MONGODB_PASSWORD}
      - RABBITMQ_URL=amqp://guest:guest@rabbitmq:5672
    depends_on:
      - mongo
      - rabbitmq
    ports:
      - ${PORT}:${PORT}
    networks:
      - app-tier

  mongo:
    image: rapidfort/mongodb-official:7.0.17-jammy
    container_name: trakto_mongodb
    restart: unless-stopped
    command: --quiet
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGODB_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGODB_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGODB_DATABASE}
    volumes:
      - mongo-data:/data/db
    ports:
      - ${MONGODB_PORT}:${MONGODB_PORT}
    networks:
      - app-tier

  rabbitmq:
    image: rabbitmq:3.13-alpine 
    container_name: trakto_rabbitmq
    restart: unless-stopped
    ports:
      - 5672:5672
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    networks:
      - app-tier

networks:
  app-tier:
    driver: bridge

volumes:
  mongo-data: